apiVersion: apps/v1
kind: Deployment
metadata:
    name: todo-app
spec:
    replicas: 1
    selector:
        matchLabels:
            app: todo-app
            version: v1
    template:
        metadata:
            labels:
                app: todo-app
                version: v1
        spec:
            terminationGracePeriodSeconds: 30
            containers:
                - name: todo-app
                  image: kristofergauti/assignment-5-e2e-testing:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 3000