apiVersion: apps/v1
kind: Deployment
metadata:
    name: todo-app
spec:
    replicas: 1
    selector:
        matchLabels:
            app: todo-app
            version: v1
    template:
        metadata:
            labels:
                app: todo-app
                version: v1
        spec:
            containers:
                - image: kristofergauti/assignment5-e2e
                  imagePullPolicy: Always
                  name: todo-app
                  ports:
                      - containerPort: 3000
