# This is a basic workflow to help you get started with Actions

name: Cypress Tests with installation job

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
        branches: [main]
    pull_request:
        branches: [main]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    setup-node:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            # Setup node
            - name: Setup nodeJS
              uses: actions/setup-node@v2.5.1
              with:
                  node-version: 16
            - name: Cache Node Modules
              id: cache-node-modules
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.OS }}-npm-cache-
            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci
              
    setup-database:
        runs-on: ubuntu-latest
        needs: [setup-node]
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Npm install
              run: npm install
            - name: Reset database
              run: npm run prisma:reset
            - name: Migrate database
              run: npm run prisma:init
              
    cypress-run:
        runs-on: ubuntu-20.04
        needs: [setup-database]
        # Cypress Docker image with Chrome v78
        # and Firefox v70 pre-installed
        container: cypress/browsers:node12.13.0-chrome78-ff70
        steps:
          - name: Run server
            run: npm run start
          - uses: actions/checkout@v2
          - uses: cypress-io/github-action@v2
            with:
              browser: chrome
